<?php  exit();
/*
Page: /api/freelist.php?tid=2
Error: 无法使用数据库
Time2012-04-10 20:41:49
*/
?>
<?php  exit();
/*
Page: /ruc-online/login.php
Error: 无法使用数据库
Time2017-01-16 14:59:40
*/
?>
<?php  exit();
/*
Page: /ruc-online/login.php
Error: 无法使用数据库
Time2017-01-16 15:01:13
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=2768&mid=9
Error: 无法使用数据库
Time2017-02-23 11:04:32
*/
?>
<?php  exit();
/*
Page: /plus/counter.php?&aid=2768&mid=9&u=httpLHB6LHB1LHB1rucLHB7zaizhiyanLHB7comLHB7cnLHB1zaizhiLHB12768LHB7html&r=httpLHB6LHB1LHB1rucLHB7zaizhiyanLHB7comLHB7cnLHB1&t=%C9%CC%D1%A7%D4%BA%C6%F3%D2%B5%B9%DC%C0%ED%D7%A8%D2%B5%C8%CB%C1%A6%D7%CA%D4%B4%B7%BD%CF%F2%BF%CE%B3%CC%D1%D0%D0%DE%B0%E0%BC%F2%D5%C2-%D4%DA%D6%B0%D1%D0%BE%BF%C9%FA%D5%D0%C9%FA%CD%F8&hour=11
Error: 无法使用数据库
Time2017-02-23 11:04:32
*/
?>
<?php  exit();
/*
Page: /ruc-online/sys_sql_query.php
Error: Table '.\zzy_ruconline17\arc_reffer' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select count(*) From arc_reffer</font>
Time2017-10-25 13:37:51
*/
?>
<?php  exit();
/*
Page: /ruc-online/sys_sql_query.php
Error: Table '.\zzy_ruconline17\arc_reffer' is marked as crashed and should be repaired <br />Error sql: <font color='red'>Select count(*) From arc_reffer</font>
Time2017-10-25 14:03:09
*/
?>
<?php  exit();
/*
Page: /ruc-online/count_list.php
Error: Table 'zzy_ruconline17.arc_reffer' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM arc_reffer
		WHERE 1=1 LIMIT 0,1;</font>
Time2019-12-25 16:26:21
*/
?>
