<?php
$tmpdir = "05e1cd8db884ccbf";
$vtime = 20100618;
$files[0] = "dede/media_add.php";
$files[1] = "dede/album_add.php";
$files[2] = "dede/update_guide.php";
$files[3] = "plus/count.php";
$files[4] = "plus/recommend.php";
$files[5] = "plus/stow.php";
$files[6] = "plus/advancedsearch.php";
$files[7] = "include/taglib/sql.lib.php";
$files[8] = "include/dialog/select_soft_post.php";
$fileConut = 8;
$sqls[] = "20100618.sql";
?>